server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # main logs
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri /index.html;
    }

    # activity logs for signup
    location /signup {
        access_log /var/log/nginx/activity.log;
        try_files $uri /index.html;
    }

    # activity logs for login
    location /login {
        access_log /var/log/nginx/activity.log;
        try_files $uri /index.html;
    }
}
